theme: jekyll-theme-cayman
title: Technical Documentation - Blockchain Challenge 2022 - Team 8
description: This github page is the technical documentation of the smart contract for the 'EuroMouse' NFT collection.
email: sercan.ates@stud.unibas.ch
author: Sercan Ates

